### ISSUE TITLE
ライセンスは何ですか

### ISSUE THREAD

**Issue by sesameoil** [0x3939b/Carrier-PreinstallApp-Disabler#1]
ソースコードのライセンスが設定されていないように見えます。
ライセンスは何ですか？

また、ノーライセンス（一般的な著作権が適用される）であるなら、そのことを明記したほうが良いのではないでしょうか。

**Comment by 0x3939b** [comment]
ご指摘ありがとうございます。

ライセンスに関してはまだ決定しておらず、とりあえず公開という手段をとっております。
近日中にライセンスを設定する予定ですので、よろしくお願いいたします。

**Comment by sesameoil** [comment]
よろしくお願いします。

**Comment by 0x3939b** [comment]
GPL-3.0 ライセンスを適用しました。
ご確認お願いいたします。
